### PR TITLE
unit test settings do not need a database router

### PR DESCRIPTION
**Pull request by elliottyates**

### CODE REVIEW

**Comment by rascalking** [comment]
Only slight hesitation I have is if we later go in and move the router down from local.py into base.py, we're not overriding it in test_settings, and the unit tests may actually want to override what ends up in base.py.

**Comment by elliottyates** [comment]
@rascalking (dave) seems like in that case the unit tests will fail, and we'll fix it before checking it in / putting it up for review...?

**Comment by rascalking** [comment]
We might also end up running migrations against the qa db before we intend to.  I don't think that's a huge issue, just worth calling out so we think it over.  In any case, the change looks fine.  :+1:

**Comment by rascalking** [comment]
:+1:

**Pull request merged**
