### PR TITLE
Feature/log management commands to separate file

### PR DESCRIPTION
**Pull request by bermudezjd**
Clean out mounds of cruft from settings files (beginning of several passes I suspect) like unnecessary gunicorn installation, commented out paragraphs, etc. Log custom management commands to a separate "django-jobs" prefixed log file that can be searched for in splunk. Move log settings to base.

### CODE REVIEW

**Comment by elliottyates** [comment]
:+1: looks good to me. Do you mind associating it with a JIRA issue (Technical Debt) that we can pull into the sprint so PM and QA are aware of all the changes for the next release? Also, should we consider making `tech_mail` a different type of filename too, for a different kind of Splunk ingestion? Probably not important for now, just throwing it out there.

**Comment by elliottyates** [comment]
Ah - you could use https://jira.huit.harvard.edu/browse/TLT-550

**Comment by bermudezjd** [comment]
@elliottyates I didn't realize what the `tech_mail` logger was, but I see it's used in the management commands to generate an error email.  The `canvas_course_site_wizard.management` logger includes `mail_admins` as a handler already, so I think you're going to get the same effect of an error email by using the module logger (the non-tech_logger in those management commands).  I can make the associated change in ccsw, or you can make the change to the wizard and I can later circle back and remove the `tech_mail` logger.

**Comment by bermudezjd** [comment]
Made a comment in the associated JIRA issue that this PR meets that request.

**Pull request merged**
